### ISSUE TITLE
make this work in python 3.11

### ISSUE THREAD

**Issue by jlillo** [Romain-Thomas-Shef/dfitspy#19]
Hello Romain,

I can't make dfitspy work in python 3.11. I get a bunge of errors related with libmagic in my MacOS M1 with Sonora when you "import magic". Any ideas?

Thanks!
Jorge

**Comment by Romain-Thomas-Shef** [comment]
Hi @jlillo!
Long time no see! Hope you are doing well!
I do have the plan to do a full update of dfitspy. It will be working with recent systems.

**Comment by jlillo** [comment]
Hi Romain,
The issue arises when importing the magic module apparently. Here I copy what I get when simply running "dfitspy" on a terminal with Python3.11.5 on a MacOS with Sonoma (14.4.1) and Apple M1 chip:

```
Traceback (most recent call last):
  File "/Users/lillo_box/.local/bin/dfitspy", line 5, in <module>
    from dfitspy.__main__ import main
  File "/Users/lillo_box/.local/lib/python3.11/site-packages/dfitspy/__init__.py", line 5, in <module>
    from dfitspy.get_files_and_keys import get_files, get_keys
  File "/Users/lillo_box/.local/lib/python3.11/site-packages/dfitspy/get_files_and_keys.py", line 14, in <module>
    import magic
  File "/Users/lillo_box/anaconda3/lib/python3.11/site-packages/magic/__init__.py", line 1, in <module>
    from .magic import *
  File "/Users/lillo_box/anaconda3/lib/python3.11/site-packages/magic/magic.py", line 167, in <module>
    libmagic = ctypes.CDLL(dll)
               ^^^^^^^^^^^^^^^^
  File "/Users/lillo_box/anaconda3/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/lillo_box/anaconda3/lib/python3.11/site-packages/magic/libmagic/libmagic.dylib, 0x0006): tried: '/Users/lillo_box/anaconda3/lib/python3.11/site-packages/magic/libmagic/libmagic.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/lillo_box/anaconda3/lib/python3.11/site-packages/magic/libmagic/libmagic.dylib' (no such file), '/Users/lillo_box/anaconda3/lib/python3.11/site-packages/magic/libmagic/libmagic.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

Thanks for any help.
